CREATE TABLE `clientes` (
  `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(60) DEFAULT NULL,
  `CIDADE` varchar(60) DEFAULT NULL,
  `UF` char(2) DEFAULT NULL,
  PRIMARY KEY (`CODIGO`)
) ;

INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('HELTON MELO'     , 'JABOATÃO','PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('JOÃO BOSCO'      , 'JABOATÃO','PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('JOÃO MATEUS'     , 'RECIFE'  ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('HELENA MARQUES'  , 'RECIFE'  ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('SANDRO SILVA'    , 'CABO'    ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('ITALO JOSÉ'      , 'CABO'    ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('HENRIQUE SILVA'  , 'IPOJUCA' ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('SEVERINO JOSÉ'   , 'IPOJUCA' ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('MARIA TEREZINHA' , 'PAULISTA','PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('CLEISON SILVA'   , 'PAULISTA','PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('CLAUDOMIRO BIU'  , 'PAULISTA','PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('FLÁVIO JOSÉ'     , 'JABOATÃO','PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('IAN FERNANDES'   , 'RECIFE'  ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('WIL BIBINON'     , 'CABO'    ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('CHAQUIRA CANTORA', 'ALDEIA'  ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('XUXA MENEGUEL'   , 'ALDEIA'  ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('ROBERTO CARLOS'  , 'CARUARU' ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('RUI BARBOSA'     , 'CARUARU' ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('MARILIA MENDONÇA', 'CARUARU' ,'PE');
INSERT INTO CLIENTES (NOME, CIDADE, UF)VALUES ('PICAPAU ARTISTA' , 'MORENO'  ,'PE');
COMMIT;