CREATE TABLE `pedidos` (
  `NUM_PEDIDO` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_EMISSAO` date DEFAULT NULL,
  `CODIGO_CLIENTE` int(11) NOT NULL,
  `VALOR_TOTAL` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`NUM_PEDIDO`)
) ;


CREATE TABLE `pedidos_produtos` (
  `CODIGO` int(11) NOT NULL AUTO_INCREMENT,
  `NUM_PEDIDO` int(11) NOT NULL,
  `CODIGO_PRODUTO` int(11) NOT NULL,
  `QUANTIDADE` int(11) NOT NULL,
  `VALOR_UNITARIO` decimal(15,2) DEFAULT NULL,
  `VALOR_TOTAL` decimal(15,2) DEFAULT NULL,
  PRIMARY KEY (`CODIGO`),
  KEY `fk_num_pedido` (`NUM_PEDIDO`),
  CONSTRAINT `fk_num_pedido` FOREIGN KEY (`NUM_PEDIDO`) REFERENCES `pedidos` (`NUM_PEDIDO`),
  CONSTRAINT `fk_produtos` FOREIGN KEY (`CODIGO`) REFERENCES `produtos` (`CODIGO`)
);
  
