CREATE TABLE `wk_db`.`pedidos` (
  `NUM_PEDIDO` INT NOT NULL AUTO_INCREMENT,
  `DATA_EMISSAO` DATE NULL,
  `CODIGO_CLIENTE` INT NOT NULL,
  `VALOR_TOTAL` DECIMAL(15,2) NULL,
  PRIMARY KEY (`NUM_PEDIDO`));


CREATE TABLE `wk_db`.`pedidos_produtos` (
  `CODIGO` INT NOT NULL AUTO_INCREMENT,  
  `NUM_PEDIDO` INT NOT NULL,
  `CODIGO_PRODUTO` INT NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  `VALOR_UNITARIO` DECIMAL(15,2) NULL,
  `VALOR_TOTAL` DECIMAL(15,2) NULL,
  PRIMARY KEY (`CODIGO`),
  FOREIGN KEY `fk_produtos` (`CODIGO`) REFERENCES `wk_db`.`produtos`(`CODIGO`));
  
